<a href="https://colab.research.google.com/github/soobin2121/ML_EDU/blob/master/%EA%B5%90%EC%B0%A8%EA%B2%80%EC%A6%9D_%EC%97%B0%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 교차 검증
- 교차 검증의 의미

- 실습

### 방법 1. 홀드아웃
- 데이터: 훈련데이터와 테스트데이터

  + 훈련데이터 : 훈련데이터 + 검증데이터 --> 테스트데이터

### 방법 2. K홀드 교차검증
- 모형이 안정성을 갖춤

- 데이터의 수가 적을 때 사용
 
  why? Default 연산량 X k개 만큼

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from scipy import stats
from sklearn.datasets import load_boston


/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [5]:
%matplotlib inline
boston = load_boston()

bostonDF = pd.DataFrame(boston.data, columns=boston.feature_names)
bostonDF['PRICE']=boston.target

print('Size of Dataset:', bostonDF.shape)

Size of Dataset: (506, 14)


In [24]:
bostonDF.head()

CRIM    ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  PRICE
0  0.00632  18.0   2.31   0.0  0.538  ...  296.0     15.3  396.90   4.98   24.0
1  0.02731   0.0   7.07   0.0  0.469  ...  242.0     17.8  396.90   9.14   21.6
2  0.02729   0.0   7.07   0.0  0.469  ...  242.0     17.8  392.83   4.03   34.7
3  0.03237   0.0   2.18   0.0  0.458  ...  222.0     18.7  394.63   2.94   33.4
4  0.06905   0.0   2.18   0.0  0.458  ...  222.0     18.7  396.90   5.33   36.2

[5 rows x 14 columns]

### 데이터 탐색
- 시각화, 통계 검정

- 변수 정의

## 머신러닝 모형 만들기

- train set 70%, test set 30%의 비율로 무작위 추출(random sampling, shuffle=True)


In [25]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# 훈련데이터, 테스트 분리

y_target = bostonDF['PRICE']
x_data = bostonDF.drop(['PRICE'], axis = 1, inplace = False)

x_train, x_test, y_train, y_test = train_test_split(x_data, y_target, test_size = 0.3, random_state = 1)       # train : test = 7 : 3

x_train, x_test, y_train, y_test


(        CRIM    ZN  INDUS  CHAS    NOX  ...   RAD    TAX  PTRATIO       B  LSTAT
 13   0.62976   0.0   8.14   0.0  0.538  ...   4.0  307.0     21.0  396.90   8.26
 61   0.17171  25.0   5.13   0.0  0.453  ...   8.0  284.0     19.7  378.08  14.44
 377  9.82349   0.0  18.10   0.0  0.671  ...  24.0  666.0     20.2  396.90  21.24
 39   0.02763  75.0   2.95   0.0  0.428  ...   3.0  252.0     18.3  395.63   4.32
 365  4.55587   0.0  18.10   0.0  0.718  ...  24.0  666.0     20.2  354.70   7.12
 ..       ...   ...    ...   ...    ...  ...   ...    ...      ...     ...    ...
 255  0.03548  80.0   3.64   0.0  0.392  ...   1.0  315.0     16.4  395.18   9.25
 72   0.09164   0.0  10.81   0.0  0.413  ...   4.0  305.0     19.2  390.91   5.52
 396  5.87205   0.0  18.10   0.0  0.693  ...  24.0  666.0     20.2  396.90  19.37
 235  0.33045   0.0   6.20   0.0  0.507  ...   8.0  307.0     17.4  376.75  10.88
 37   0.08014   0.0   5.96   0.0  0.499  ...   5.0  279.0     19.2  396.90   8.77
 
 [354 rows x 1

In [13]:
#모형 만들기 = 선형회귀

Ir_model = LinearRegression()
Ir_model.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [17]:
# 예측

y_preds = Ir_model.predict(x_test)
y_preds

array([32.3914647 , 27.94401279, 17.83762764, 21.66941388, 18.93639614,
       20.01995795, 32.63414961, 17.86179976, 24.73211676, 26.77346826,
       27.26138023, 28.63243014, 21.16103038, 27.15098589, 23.33198614,
       21.02894005, 17.11819755, 37.52455938, 30.69864427,  8.46104486,
       20.83966032, 16.26732451, 25.05030307, 24.8069032 , 31.6789299 ,
       10.98989363, 13.54111562, 16.54697099, 35.86699683, 14.69589266,
       21.05655107, 13.90301353, 43.01321262, 17.80335305, 21.68817023,
       20.45077825, 17.38095983, 26.81334904, 10.08706217, 19.96174586,
       24.1983249 , 21.00202622, 29.38682967, 16.33215467, 19.37439646,
       14.45525235, 39.52670798, 18.18535021, 26.38536303, 20.41420863,
       25.08511581, 24.40208165, 24.87902769, 26.97887956,  4.93921657,
       24.0001365 , 10.66711602, 26.98494775, 16.63507993, 35.31652989,
       19.49249915, 27.37577863, 16.53965715, 19.09746715, 11.06765336,
       32.03445261, 36.15847648, 21.53547868, 24.96434626, 25.50

- mean_squared_error(MSE): 실제값과 예측값의 차이를 제곱 후 평균

In [16]:
mse = mean_squared_error(y_test, y_preds)
mse

19.831323672062922

In [18]:
rmse = np.sqrt(mse)
rmse

4.4532374371981245

## K 폴드 적용
- cross_val_score() 함수 활용해서 RMSE

- 설정 : 5번의 폴드값

In [20]:
from sklearn.model_selection import cross_val_score
neg_mse_scores= cross_val_score(Ir_model, x_data, y_target, scoring='neg_mean_squared_error', cv=5)
# 반환되는 숫자가 음수값 

neg_mse_scores

array([-12.46030057, -26.04862111, -33.07413798, -80.76237112,
       -33.31360656])

In [22]:
# 그래서 양수로 변환

rmse_scores = np.sqrt(-1 * neg_mse_scores)
rmse_scores

array([3.52991509, 5.10378498, 5.75101191, 8.9867887 , 5.77179405])

In [23]:
# 평균값 구하기

avg_rmse = np.mean(rmse_scores)
avg_rmse

5.828658946215802